# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodTracker
  pod 'ObjectMapper', '~> 2.0'
  pod 'BMSCore', '~> 2.0'

  target 'FoodTrackerTests' do
    inherit! :search_paths
    pod 'ObjectMapper', '~> 2.0'
    pod 'BMSCore', '~> 2.0'
    # Pods for testing
  end

end
